import {
  BellRing,
  CalendarClock,
  CalendarDays,
  Database,
  History,
  LayoutGrid,
  ListChecks,
  Layers,
  Map,
  MapPin,
  Radio,
  Rss,
  Trophy,
  MessageSquare,
} from "lucide-react";
import type { CommandPaletteItemDef } from "./commandPaletteTypes";

export const COMMAND_PALETTE_NAVIGATION_DEFS: readonly CommandPaletteItemDef[] = [
  { id: "monitor", labelKey: "monitor", labelNs: "nav", to: "/monitor", icon: Radio, groupId: "navigation", keywords: ["monitor", "stream"] },
  {
    id: "board",
    labelKey: "commandPalette.openOpsBoard",
    action: "open-board",
    icon: LayoutGrid,
    groupId: "navigation",
    hintKey: "commandPalette.openOpsBoardHint",
    keywords: ["ops", "board", "canvas", "畫布", "画布", "ops board"],
  },
  { id: "monitor-wall", labelKey: "commandPalette.monitorWall", to: "/monitor?view=wall", icon: Radio, groupId: "navigation", keywords: ["wall", "看板"] },
  { id: "tasks", labelKey: "tasks", labelNs: "nav", to: "/tasks", icon: ListChecks, groupId: "navigation", keywords: ["task"] },
  {
    id: "worksets",
    labelKey: "worksets",
    labelNs: "nav",
    to: "/worksets",
    icon: Layers,
    groupId: "navigation",
    keywords: ["workset", "工作集"],
  },
  {
    id: "schedule",
    labelKey: "schedule",
    labelNs: "nav",
    to: "/schedule",
    icon: CalendarClock,
    groupId: "navigation",
    keywords: ["schedule", "calendar", "日程", "循环"],
  },
  { id: "leaderboard", labelKey: "leaderboard", labelNs: "nav", to: "/leaderboard", icon: Trophy, groupId: "navigation" },
  { id: "intelligence", labelKey: "keyEvents", labelNs: "nav", to: "/intelligence", icon: MapPin, groupId: "navigation", keywords: ["intel"] },
  {
    id: "intelligence-map",
    labelKey: "commandPalette.keyEventsMap",
    to: "/intelligence?view=map",
    icon: Map,
    groupId: "navigation",
    keywords: ["map", "地圖"],
  },
  {
    id: "intelligence-list",
    labelKey: "commandPalette.keyEventsList",
    to: "/intelligence?view=list",
    icon: MapPin,
    groupId: "navigation",
    keywords: ["list"],
  },
  {
    id: "intelligence-card",
    labelKey: "commandPalette.keyEventsCard",
    to: "/intelligence?view=card",
    icon: MapPin,
    groupId: "navigation",
    keywords: ["card"],
  },
  { id: "timeline", labelKey: "timeline", labelNs: "nav", to: "/timeline", icon: CalendarDays, groupId: "navigation" },
  { id: "actions", labelKey: "actions", labelNs: "nav", to: "/actions", icon: BellRing, groupId: "navigation" },
  {
    id: "actions-voice",
    labelKey: "commandPalette.actionsVoice",
    to: "/actions?tab=notify",
    icon: BellRing,
    groupId: "navigation",
    keywords: ["voice", "語音", "語音提醒", "语音提醒", "本機通知", "本机通知", "通知", "提醒", "閃現", "闪现"],
  },
  {
    id: "actions-history",
    labelKey: "commandPalette.actionsHistory",
    to: "/actions?tab=history",
    icon: History,
    groupId: "navigation",
    keywords: ["history", "紀錄", "觸發"],
  },
  { id: "sources", labelKey: "sources", labelNs: "nav", to: "/sources", icon: Database, groupId: "navigation", keywords: ["source"] },
  {
    id: "assistant",
    labelKey: "assistant",
    labelNs: "nav",
    to: "/assistant",
    icon: MessageSquare,
    groupId: "navigation",
    keywords: ["assistant", "語音", "chat", "日程", "AI 助手"],
  },
  {
    id: "sources-rss",
    labelKey: "commandPalette.sourcesRss",
    to: "/sources?tab=rss",
    icon: Rss,
    groupId: "navigation",
    keywords: ["rss", "folo"],
  },
  {
    id: "sources-telegram",
    labelKey: "commandPalette.sourcesTelegram",
    to: "/sources?tab=telegram",
    icon: Database,
    groupId: "navigation",
    keywords: ["telegram"],
  },
  {
    id: "sources-discord",
    labelKey: "commandPalette.sourcesDiscord",
    to: "/sources?tab=discord",
    icon: Database,
    groupId: "navigation",
    keywords: ["discord"],
  },
  {
    id: "sources-http",
    labelKey: "commandPalette.sourcesHttp",
    to: "/sources?tab=http",
    icon: Database,
    groupId: "navigation",
    keywords: ["http", "抓取", "poll"],
  },
  {
    id: "sources-http-webhook",
    labelKey: "commandPalette.sourcesHttpWebhook",
    to: "/sources?tab=http&mode=webhook",
    icon: Database,
    groupId: "navigation",
    keywords: ["webhook", "api key", "ingestion"],
  },
  {
    id: "sources-mqtt",
    labelKey: "commandPalette.sourcesMqtt",
    to: "/sources?tab=mqtt",
    icon: Database,
    groupId: "navigation",
    keywords: ["mqtt", "broker"],
  },
  {
    id: "sources-email",
    labelKey: "commandPalette.sourcesEmail",
    to: "/sources?tab=email",
    icon: Database,
    groupId: "navigation",
    keywords: ["email", "imap", "郵件"],
  },
];
