/** Build theme.generated.css from the catalog (used by scripts/generate-theme-css.mjs). */

import type { ThemeColors, ThemeDefinition } from "./themeTypes.ts";
import { CLASSIC_MOTION, DESK_MOTION, THEME_CATALOG } from "./themeCatalogData.ts";

/** Flat string tokens only — nested groups (platform / wallBanners / calendarDot) emit separately. */
type ScalarColorKey = {
  [K in keyof ThemeColors]-?: NonNullable<ThemeColors[K]> extends string ? K : never;
}[keyof ThemeColors];

const COLOR_VAR_MAP: Array<[ScalarColorKey, string]> = [
  ["textPrimary", "--text-primary"],
  ["textSecondary", "--text-secondary"],
  ["textMuted", "--text-muted"],
  ["textSubtle", "--text-subtle"],
  ["accent", "--accent"],
  ["accentPink", "--accent-pink"],
  ["info", "--info"],
  ["success", "--success"],
  ["warning", "--warning"],
  ["error", "--error"],
  ["surfaceBase", "--surface-base"],
  ["surfaceCard", "--surface-card"],
  ["surfaceBorder", "--surface-border"],
  ["surfaceOverlay", "--surface-overlay"],
  ["peach", "--peach"],
  ["lavender", "--lavender"],
  ["shadowSm", "--shadow-sm"],
  ["shadowMd", "--shadow-md"],
  ["shadowLg", "--shadow-lg"],
  ["shadowXl", "--shadow-xl"],
  ["surfaceGradient", "--surface-gradient"],
  ["surfaceBorderAlpha", "--surface-border-alpha"],
  ["textOnAccent", "--text-on-accent"],
  ["themeBg", "--theme-bg"],
  ["themeGlow", "--theme-glow"],
  ["glassBg", "--glass-bg"],
  ["glassBorder", "--glass-border"],
  ["glassBlur", "--glass-blur"],
  ["imPageGlow", "--im-page-glow"],
];

function emitThemeBlock(theme: ThemeDefinition): string {
  const lines: string[] = [`[data-theme="${theme.id}"] {`];
  const c = theme.colors;

  for (const [key, cssVar] of COLOR_VAR_MAP) {
    const val = c[key];
    if (val != null && val !== "") {
      lines.push(`  ${cssVar}: ${val};`);
    }
  }

  if (c.platform) {
    for (const [plat, val] of Object.entries(c.platform)) {
      if (val) lines.push(`  --platform-${plat}: ${val};`);
    }
  }

  if (c.wallBanners) {
    for (const [n, val] of Object.entries(c.wallBanners)) {
      lines.push(`  --wall-banner-${n}: ${val};`);
    }
  }

  if (c.calendarDot) {
    if (c.calendarDot.event) lines.push(`  --calendar-dot-event: ${c.calendarDot.event};`);
    if (c.calendarDot.ongoing) lines.push(`  --calendar-dot-ongoing: ${c.calendarDot.ongoing};`);
    if (c.calendarDot.ending) lines.push(`  --calendar-dot-ending: ${c.calendarDot.ending};`);
  }

  // Per-theme motion tokens (family defaults; special themes refine further)
  lines.push(`  --im-duration-fast: ${theme.motion.durationFast};`);
  lines.push(`  --im-duration-normal: ${theme.motion.durationNormal};`);
  lines.push(`  --im-easing-out: ${theme.motion.easingOut};`);
  lines.push(`  --im-stagger-step: ${theme.motion.staggerStep};`);

  lines.push("}");
  return lines.join("\n");
}

/** Generate the contents of theme.generated.css */
export function generateThemeCss(): string {
  const header = [
    "/* AUTO-GENERATED by scripts/generate-theme-css.mjs — do not edit by hand. */",
    "/* Source: web/src/styles/themeCatalog.ts */",
    "",
  ].join("\n");

  // Family defaults first; per-theme blocks win on equal specificity.
  const familyMotion = [
    "/* Family-level motion defaults (per-theme blocks below override) */",
    '[data-theme-family="desk"] {',
    `  --im-duration-fast: ${DESK_MOTION.durationFast};`,
    `  --im-duration-normal: ${DESK_MOTION.durationNormal};`,
    `  --im-easing-out: ${DESK_MOTION.easingOut};`,
    `  --im-stagger-step: ${DESK_MOTION.staggerStep};`,
    "}",
    "",
    '[data-theme-family="classic"] {',
    `  --im-duration-fast: ${CLASSIC_MOTION.durationFast};`,
    `  --im-duration-normal: ${CLASSIC_MOTION.durationNormal};`,
    `  --im-easing-out: ${CLASSIC_MOTION.easingOut};`,
    `  --im-stagger-step: ${CLASSIC_MOTION.staggerStep};`,
    "}",
    "",
    '[data-theme-family="special"] {',
    "  /* cyberpunk / sakura set motion on [data-theme] */",
    "}",
  ].join("\n");

  const blocks = THEME_CATALOG.map(emitThemeBlock).join("\n\n");

  // Special glass / bg effects keyed by family (not a 9-id :is() list)
  const specialEffects = [
    "",
    '/* Special family — glass + glow (data-theme-family="special") */',
    '[data-theme-family="special"] body {',
    "  background: var(--theme-bg);",
    "}",
    "",
    '[data-theme-family="special"] body::before {',
    "  content: '';",
    "  position: fixed;",
    "  inset: 0;",
    "  background: var(--theme-glow);",
    "  pointer-events: none;",
    "  z-index: 0;",
    "}",
    "",
    '[data-theme-family="special"] :is(.im-card-hover) {',
    "  background: var(--glass-bg);",
    "  border-color: var(--glass-border);",
    "  -webkit-backdrop-filter: blur(var(--glass-blur));",
    "  backdrop-filter: blur(var(--glass-blur));",
    "}",
  ].join("\n");

  return `${header}${familyMotion}\n\n${blocks}\n${specialEffects}\n`;
}
