/** Classic-family paper (light) theme catalog entries. */

import type { ThemeDefinition } from "./themeTypes.ts";
import {
  CLASSIC_MOTION,
  LIGHT_SHADOWS,
  WASHI_SHADOWS,
  accentWash,
} from "./themeCatalogShared.ts";

export const THEME_CATALOG_CLASSIC_PAPER: readonly ThemeDefinition[] = [
  {
      id: "latte",
      name: "Latte",
      family: "classic",
      light: true,
      texture: "linen",
      swatch: ["#e8ecf4", "#ffffff", "#1d4ed8", "#c2410c", "#1e293b"],
      motion: CLASSIC_MOTION,
      colors: {
        textPrimary: "#1e293b",
        textSecondary: "#475569",
        textMuted: "#64748b",
        textSubtle: "#94a3b8",
        accent: "#1d4ed8",
        accentPink: "#db2777",
        info: "#0284c7",
        success: "#15803d",
        warning: "#c2410c",
        error: "#dc2626",
        surfaceBase: "#e8ecf4",
        surfaceCard: "#ffffff",
        surfaceBorder: "#c5ceda",
        surfaceOverlay: "#dde3ee",
        peach: "#ea580c",
        lavender: "#6366f1",
        ...LIGHT_SHADOWS,
        surfaceGradient: "linear-gradient(180deg, #ffffff 0%, #f5f7fb 100%)",
        surfaceBorderAlpha: "rgba(148, 163, 184, 0.45)",
        textOnAccent: "#ffffff",
        imPageGlow: accentWash("#1d4ed8", 6),
        calendarDot: { event: "#1d4ed8", ongoing: "#0e7490", ending: "#c2410c" },
      },
    },
  {
      id: "washi",
      name: "Washi",
      family: "classic",
      light: true,
      texture: "washi",
      // 和紙：暖紙底 + 墨字 + 藍灰強調（樸實明亮）
      swatch: ["#f3eee4", "#fffaf3", "#3d5a80", "#c45c3e", "#2c2824"],
      motion: CLASSIC_MOTION,
      colors: {
        textPrimary: "#2c2824",
        textSecondary: "#5c534a",
        textMuted: "#8a7f72",
        textSubtle: "#b0a498",
        accent: "#3d5a80",
        accentPink: "#a67c52",
        info: "#4a7c8c",
        success: "#5a7a5e",
        warning: "#b45309",
        error: "#b33b2e",
        surfaceBase: "#f3eee4",
        surfaceCard: "#fffaf3",
        surfaceBorder: "#d4c8b4",
        surfaceOverlay: "#ebe3d4",
        peach: "#c47a4a",
        lavender: "#7a6e8c",
        ...WASHI_SHADOWS,
        surfaceGradient: "linear-gradient(180deg, #fffaf3 0%, #f7f1e6 100%)",
        surfaceBorderAlpha: "rgba(180, 160, 130, 0.45)",
        textOnAccent: "#fffaf3",
        imPageGlow: accentWash("#3d5a80", 5),
        calendarDot: { event: "#3d5a80", ongoing: "#2a9d8f", ending: "#c45c3e" },
      },
    },
  {
      id: "orchard",
      name: "Orchard",
      family: "classic",
      light: true,
      texture: "leaf",
      // 果園：淺橄欖紙底 + 蘋果紅 + 葉綠（自然亮色）
      swatch: ["#eef2e6", "#fbfaf4", "#c0453a", "#5a8a4a", "#2a3224"],
      motion: CLASSIC_MOTION,
      colors: {
        textPrimary: "#2a3224",
        textSecondary: "#4a5640",
        textMuted: "#6e7a62",
        textSubtle: "#9aa48e",
        accent: "#c0453a",
        accentPink: "#a06040",
        info: "#4a7a8a",
        success: "#5a8a4a",
        warning: "#b07820",
        error: "#b03830",
        surfaceBase: "#eef2e6",
        surfaceCard: "#fbfaf4",
        surfaceBorder: "#c8d0b8",
        surfaceOverlay: "#e4e8d8",
        peach: "#c47840",
        lavender: "#7a6a8a",
        ...WASHI_SHADOWS,
        surfaceGradient: "linear-gradient(180deg, #fbfaf4 0%, #f2f4ea 100%)",
        surfaceBorderAlpha: "rgba(160, 170, 140, 0.45)",
        textOnAccent: "#fbfaf4",
        imPageGlow: accentWash("#5a8a4a", 5),
        calendarDot: { event: "#c0453a", ongoing: "#3a6a9a", ending: "#5a8a4a" },
      },
    },
  {
      id: "mist",
      name: "Mist",
      family: "classic",
      light: true,
      texture: "mist",
      // 薄霧：冷灰藍紙 + 石板藍 + 暖琥珀點綴
      swatch: ["#e6eaef", "#f7f9fb", "#4a6280", "#c47840", "#243040"],
      motion: CLASSIC_MOTION,
      colors: {
        textPrimary: "#243040",
        textSecondary: "#4a5a6a",
        textMuted: "#6e7e8e",
        textSubtle: "#9aa8b4",
        accent: "#4a6280",
        accentPink: "#8a6070",
        info: "#3a7a9a",
        success: "#4a8a6a",
        warning: "#c47840",
        error: "#b05050",
        surfaceBase: "#e6eaef",
        surfaceCard: "#f7f9fb",
        surfaceBorder: "#c0cad4",
        surfaceOverlay: "#dde4ea",
        peach: "#c48860",
        lavender: "#707898",
        ...LIGHT_SHADOWS,
        surfaceGradient: "linear-gradient(180deg, #f7f9fb 0%, #eef2f6 100%)",
        surfaceBorderAlpha: "rgba(140, 155, 170, 0.45)",
        textOnAccent: "#f7f9fb",
        imPageGlow: accentWash("#4a6280", 5),
        calendarDot: { event: "#4a6280", ongoing: "#1a9a88", ending: "#c47840" },
      },
    },
  {
      id: "porcelain",
      name: "Porcelain",
      family: "classic",
      light: true,
      texture: "frost",
      // 青瓷：冷白瓷底 + 青磁綠 + 靛青字（非奶油陶土）
      swatch: ["#eef4f2", "#fbfdfe", "#2a7a6a", "#3d5a80", "#1e2e2c"],
      motion: CLASSIC_MOTION,
      colors: {
        textPrimary: "#1e2e2c",
        textSecondary: "#3e524e",
        textMuted: "#6a7e78",
        textSubtle: "#9aada6",
        accent: "#2a7a6a",
        accentPink: "#8a6070",
        info: "#3d6a9a",
        success: "#3a8a5a",
        warning: "#b45309",
        error: "#b33b3b",
        surfaceBase: "#eef4f2",
        surfaceCard: "#fbfdfe",
        surfaceBorder: "#c8d8d2",
        surfaceOverlay: "#e4eeea",
        peach: "#c47a4a",
        lavender: "#6a7a9a",
        ...LIGHT_SHADOWS,
        surfaceGradient: "linear-gradient(180deg, #fbfdfe 0%, #f0f6f4 100%)",
        surfaceBorderAlpha: "rgba(140, 165, 155, 0.4)",
        textOnAccent: "#fbfdfe",
        imPageGlow: accentWash("#2a7a6a", 5),
        // Ongoing saturates past --info (#3d6a9a), which muddies into the celadon accent dot.
        calendarDot: { event: "#2a7a6a", ongoing: "#2563eb", ending: "#b45309" },
      },
    }
];
