"""Response models for drift-prone API routes (camelCase wire format).

Grouped by domain in the sibling modules; routes and tests import them from
this package, so a model can move between modules without touching callers.
"""

from __future__ import annotations

from server.api.schemas.responses.accounts import (
    AccountResponse,
    AddAccountResponse,
    AddDiscordBotResponse,
    AddEmailMailboxResponse,
    AddHttpSourceResponse,
    AddMqttBrokerResponse,
    AddRssFeedResponse,
    DiscordBotInfoResponse,
    DiscordChannelInfoResponse,
    DiscordSubscribeResponse,
    EmailMailboxInfoResponse,
    HttpSourceInfoResponse,
    MqttBrokerInfoResponse,
    RefreshAllAccountsResponse,
    RssFeedInfoResponse,
    UpdateTelegramAccountResponse,
)
from server.api.schemas.responses.actions import (
    ActionResponse,
    ActionTestResponse,
    ActionToggleResponse,
    ActionTriggerHistoryEntryResponse,
    ActionTriggerHistoryPageResponse,
)
from server.api.schemas.responses.auth import (
    AccessKeyCreatedResponse,
    AccessKeyDeleteResponse,
    AccessKeyListResponse,
    AccessKeyPublicResponse,
    DeviceInfoResponse,
    DeviceSessionTokensResponse,
    SetupStatusResponse,
)
from server.api.schemas.responses.events import (
    AnalysisEventResponse,
    AnalysisEventsPageResponse,
    CalendarOccurrenceResponse,
    TimelineDismissalResponse,
    TrendingTopicResponse,
    UserEventResponse,
)
from server.api.schemas.responses.logs import (
    AppLogCursorResponse,
    AppLogEntryResponse,
    AppLogPageResponse,
)
from server.api.schemas.responses.messages import (
    ChannelResponse,
    ChannelWithAccountResponse,
    MessageCursorResponse,
    MessageMediaResponse,
    MessageResponse,
    MessagesIngestBatchResponse,
    MessagesPageResponse,
)
from server.api.schemas.responses.system import (
    RetentionDeletedCounts,
    RetentionRunResponse,
    SchemaUpgradeProgress,
    SchemaUpgradeStatusResponse,
    SystemSettingsSnapshot,
)
from server.api.schemas.responses.tasks import (
    AgentChatResponse,
    AgentToolCallSummary,
    ChannelRefResponse,
    ChatAssistantResponse,
    ProjectTickInFlightResponse,
    ProjectTickLogEntryResponse,
    ProjectTickStatusResponse,
    QueueBatchResponse,
    ResultsQueueResponse,
    TaskActivitySpanResponse,
    TaskAnalysisStatsResponse,
    TaskDeleteResponse,
    TaskDraftPayload,
    TaskResponse,
)
from server.api.schemas.responses.ui_prefs import (
    AssistantSessionsResponse,
    AssistantVoiceIoResponse,
    BoardPrefsResponse,
    TimelineAnnotationsResponse,
    VoiceReminderFiredClaimResponse,
    VoiceReminderFiredResponse,
    VoiceReminderHistoryResponse,
    VoiceReminderSettingsResponse,
)
from server.api.schemas.responses.viewer import (
    ViewerStatsResponse,
    ViewerStatusResponse,
    ViewerTaskResponse,
)
from server.api.schemas.responses.weather import (
    WeatherDailyResponse,
    WeatherForecastResponse,
)

__all__ = [
    "AccessKeyCreatedResponse",
    "AccessKeyDeleteResponse",
    "AccessKeyListResponse",
    "AccessKeyPublicResponse",
    "AccountResponse",
    "ActionResponse",
    "ActionTestResponse",
    "ActionToggleResponse",
    "ActionTriggerHistoryEntryResponse",
    "ActionTriggerHistoryPageResponse",
    "AddAccountResponse",
    "AddDiscordBotResponse",
    "AddEmailMailboxResponse",
    "AddHttpSourceResponse",
    "AddMqttBrokerResponse",
    "AddRssFeedResponse",
    "AgentChatResponse",
    "AgentToolCallSummary",
    "AnalysisEventResponse",
    "AnalysisEventsPageResponse",
    "AppLogCursorResponse",
    "AppLogEntryResponse",
    "AppLogPageResponse",
    "AssistantSessionsResponse",
    "AssistantVoiceIoResponse",
    "BoardPrefsResponse",
    "CalendarOccurrenceResponse",
    "ChannelRefResponse",
    "ChannelResponse",
    "ChannelWithAccountResponse",
    "ChatAssistantResponse",
    "DeviceInfoResponse",
    "DeviceSessionTokensResponse",
    "DiscordBotInfoResponse",
    "DiscordChannelInfoResponse",
    "DiscordSubscribeResponse",
    "EmailMailboxInfoResponse",
    "HttpSourceInfoResponse",
    "MessageCursorResponse",
    "MessageMediaResponse",
    "MessageResponse",
    "MessagesIngestBatchResponse",
    "MessagesPageResponse",
    "MqttBrokerInfoResponse",
    "ProjectTickLogEntryResponse",
    "ProjectTickInFlightResponse",
    "ProjectTickStatusResponse",
    "QueueBatchResponse",
    "ResultsQueueResponse",
    "RetentionDeletedCounts",
    "RetentionRunResponse",
    "RefreshAllAccountsResponse",
    "RssFeedInfoResponse",
    "SchemaUpgradeProgress",
    "SchemaUpgradeStatusResponse",
    "SetupStatusResponse",
    "SystemSettingsSnapshot",
    "TaskActivitySpanResponse",
    "TaskAnalysisStatsResponse",
    "TaskDeleteResponse",
    "TaskDraftPayload",
    "TaskResponse",
    "TimelineAnnotationsResponse",
    "TimelineDismissalResponse",
    "TrendingTopicResponse",
    "UpdateTelegramAccountResponse",
    "UserEventResponse",
    "ViewerStatsResponse",
    "ViewerStatusResponse",
    "ViewerTaskResponse",
    "VoiceReminderFiredClaimResponse",
    "VoiceReminderFiredResponse",
    "VoiceReminderHistoryResponse",
    "VoiceReminderSettingsResponse",
    "WeatherDailyResponse",
    "WeatherForecastResponse",
]
