"""Request models grouped by API domain."""

from server.api.schemas.requests.actions import ActionBody
from server.api.schemas.requests.agents import A2aAgentBody, AgentChatBody
from server.api.schemas.requests.auth import (
    AccessKeyCreateBody,
    ChangePasswordBody,
    LoginBody,
    RefreshBody,
    RegisterBody,
    ResetPasswordBody,
    RotateSecretsBody,
)
from server.api.schemas.requests.calendar import (
    CalendarImportCommitBody,
    CalendarImportInput,
    CalendarImportSelectionBody,
    RecurringSeriesCreateBody,
    RecurringSeriesPatchBody,
    TimelineDismissalBody,
    TimelineImportanceBody,
    UserEventCreateBody,
    UserEventPatchBody,
)
from server.api.schemas.requests.calendar_share import (
    CalendarShareLoginBody,
    CalendarSharePublishBody,
    CalendarShareSubscribeBody,
    CalendarShareTimezoneBody,
)
from server.api.schemas.requests.items import (
    CategoryCreateBody,
    CategoryUpdateBody,
    ItemCreateBody,
    ItemUpdateBody,
)
from server.api.schemas.requests.logs import LogCreate
from server.api.schemas.requests.messages import IngestBatchBody, IngestMessageBody
from server.api.schemas.requests.sources import (
    DiscordBotBody,
    DiscordBotPatchBody,
    DiscordSubscribeBody,
    EmailMailboxBody,
    EmailMailboxPatchBody,
    HttpSourceBody,
    HttpSourcePatchBody,
    MqttBrokerBody,
    MqttBrokerPatchBody,
    RssFeedBody,
    RssFeedPatchBody,
    Telegram2faBody,
    TelegramCodeBody,
    TelegramCredentials,
    TelegramPatchBody,
    TelegramQrCredentials,
    TelegramQrWaitBody,
)
from server.api.schemas.requests.system import (
    AiEngineTestBody,
    AnalysisPauseBody,
    SystemSettingsUpdateBody,
)
from server.api.schemas.requests.tasks import TaskConfigBody, TaskPatchBody
from server.api.schemas.requests.worksets import WorksetCreateBody, WorksetUpdateBody

__all__ = [
    "A2aAgentBody",
    "AccessKeyCreateBody",
    "ActionBody",
    "AgentChatBody",
    "AiEngineTestBody",
    "AnalysisPauseBody",
    "CalendarShareLoginBody",
    "CalendarSharePublishBody",
    "CalendarShareSubscribeBody",
    "CalendarShareTimezoneBody",
    "CalendarImportCommitBody",
    "CalendarImportInput",
    "CalendarImportSelectionBody",
    "CategoryCreateBody",
    "CategoryUpdateBody",
    "ChangePasswordBody",
    "DiscordBotBody",
    "DiscordBotPatchBody",
    "DiscordSubscribeBody",
    "EmailMailboxBody",
    "EmailMailboxPatchBody",
    "HttpSourceBody",
    "HttpSourcePatchBody",
    "IngestBatchBody",
    "IngestMessageBody",
    "ItemCreateBody",
    "ItemUpdateBody",
    "LogCreate",
    "LoginBody",
    "MqttBrokerBody",
    "MqttBrokerPatchBody",
    "RssFeedBody",
    "RssFeedPatchBody",
    "RefreshBody",
    "RegisterBody",
    "ResetPasswordBody",
    "RecurringSeriesCreateBody",
    "RecurringSeriesPatchBody",
    "RotateSecretsBody",
    "SystemSettingsUpdateBody",
    "TaskConfigBody",
    "TaskPatchBody",
    "Telegram2faBody",
    "TelegramCodeBody",
    "TelegramCredentials",
    "TelegramPatchBody",
    "TelegramQrCredentials",
    "TelegramQrWaitBody",
    "TimelineDismissalBody",
    "TimelineImportanceBody",
    "UserEventCreateBody",
    "UserEventPatchBody",
    "WorksetCreateBody",
    "WorksetUpdateBody",
]
