import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const SRC_DIR = resolve(__dirname, "..");

const RETIRED_SOURCE_PATHS = [
  "pages/actions",
  "pages/actions/NotificationUI.test.tsx",
  "components/common/ViewToggle.tsx",
  "components/settings/OverlapSlider.tsx",
  "pages/tasks/chat-editor/OverlapSlider.tsx",
  "pages/tasks/chat-editor/OverlapSlider.test.tsx",
  "components/CalendarImportHost.tsx",
  "pages/logs/resolveLogDisplayMessage.ts",
  "pages/timeline/gantt/groupRecurringGanttRows.ts",
  "components/PageToolbar.tsx",
  "board/boardPersistedKeys.ts",
  "board/boardLegacyPersistedKeys.ts",
  "api/httpCore.ts",
  "domain/intelligence/intelligenceSourceFilter.ts",
  "domain/timeline/timelineSourceFilter.ts",
  "pages/timeline/timelinePanelKeys.ts",
  "pages/profile",
  "pages/tasks/chat-editor/useProjectWaveInterval.ts",
  "pages/timeline/components/UserEventDialog.tsx",
  "utils/datetime.ts",
  "hooks/useTaskForm.ts",
  "hooks/useTaskFormState.ts",
  "hooks/useTaskFormFields.ts",
  "hooks/useTaskFormValidation.ts",
  "hooks/usePersistedEnum.ts",
  "hooks/usePersistedViewMode.ts",
  "hooks/usePersistedMonitorViewMode.ts",
  "hooks/usePortaledChecklistMenu.ts",
  "pages/intelligence/useReadTracking.ts",
  "context/runtimeLogs/runtimeLogsPersistedKeys.ts",
  "domain/assistant/assistantPersistedKeys.ts",
  "domain/intelligence/intelligencePersistedKeys.ts",
  "domain/monitor/monitorPersistedKeys.ts",
  "domain/tasks/chatEditorPersistedKeys.ts",
  "domain/ui/chromePersistedKeys.ts",
  "electron/electronPersistedKeys.ts",
  "i18n/localePersistedKeys.ts",
  "pages/intelligence/map/mapPersistedKeys.ts",
  "pages/leaderboard/leaderboardPersistedKeys.ts",
  "pages/logs/logsPersistedKeys.ts",
  "pages/monitor/monitorPersistedKeys.ts",
  "pages/sources/discord/discordPersistedKeys.ts",
  "pages/timeline/timelinePersistedKeys.ts",
  "pages/viewer/viewerPersistedKeys.ts",
  "speech/voicePersistedKeys.ts",
  "styles/themePersistedKeys.ts",
  "voiceReminder",
  "pages/actions/components/VoiceReminderPanel.tsx",
  "pages/actions/hooks/useVoiceReminderPanelState.ts",
  "domain/notify/scanner/useVoiceReminderScanner.ts",
  "domain/notify/scanner/useVoiceReminderScanner.test.tsx",
  "api/uiPrefs/voiceReminder.ts",
  "components/SchemaUpgradeGate.tsx",
  "components/analysis/analysisStatusModel.ts",
  "components/ui/OverlaySelectField.test.tsx",
  "components/ui/OverlaySelectField.tsx",
  "domain/tasks/isProjectTask.ts",
  "pages/items/ItemsEntryCard.tsx",
  "pages/items/ItemsEntryCard.test.tsx",
  "pages/tasks/agent/ProjectDetailPage.tsx",
  "pages/tasks/agent/ProjectDetailPage.test.tsx",
  "pages/tasks/agent/ProjectDetailSourcesSection.tsx",
  "pages/tasks/agent/ProjectDetailTickSection.tsx",
  "pages/tasks/agent/projectDetailFormat.tsx",
  "pages/tasks/agent/projectDetailModel.ts",
  "pages/tasks/agent/projectTickSummary.ts",
  "pages/tasks/agent/projectTickSummary.test.ts",
  "pages/tasks/agent/useProjectDetail.ts",
  // Wave I — legacy /tasks/:taskId/project URL + pages/tasks/project tree retired
  "pages/tasks/project",
  "components/task/recurrenceRuleUtils.ts",
  "components/calendar/userEventFormModel.ts",
  // Wave — rrule helpers moved to domain/schedule/
  "utils/rrule.ts",
  "utils/rruleValidation.ts",
  "utils/rrule.test.ts",
  // Wave H — actions/monitor flat roots nested under hooks/ + components/
  "pages/actions/ActionCard.tsx",
  "pages/actions/ActionTypesTab.tsx",
  "pages/actions/ActionsTabNav.tsx",
  "pages/actions/VoiceReminderPanel.tsx",
  "pages/actions/useActionsPage.ts",
  "pages/actions/useActionTypeHandlers.ts",
  "pages/actions/useVoiceReminderPanelState.ts",
  "pages/monitor/MessageDetailDialog.tsx",
  "pages/monitor/MonitorCardFeed.tsx",
  "pages/monitor/MonitorToolbar.tsx",
  "pages/monitor/MonitorWallSection.tsx",
  "pages/monitor/useMonitorPage.ts",
  "pages/monitor/useMonitorData.ts",
  "pages/monitor/useMonitorHandlers.ts",
  // Assistant page — per-session LLM profile picker retired (global AI slots only)
  "components/assistant/AssistantSessionLlmProfileSelect.tsx",
  "components/assistant/AssistantSessionLlmProfileSelect.test.tsx",
  "components/WorksetCardEmoji.tsx",
] as const;

// Settings → General LAN bind toggle lived inline (no dedicated module).
// Content bans: retiredUiGuards.test.ts + FORBIDDEN_KEYS general.lanAccess*.

describe("retired source paths", () => {
  it.each(RETIRED_SOURCE_PATHS)("%s stays retired", (relativePath) => {
    expect(existsSync(resolve(SRC_DIR, relativePath))).toBe(false);
  });
});
