/** Default system settings snapshot for tests (Stamp 29 — no LLM provider slots). */
import type { SystemSettingsSnapshot } from "../types";

export const defaultSettingsSnapshot: SystemSettingsSnapshot = {
  analysisPaused: false,
  analysisBatchMessageLimit: "50",
  analysisMaxTotalChars: "100000",
  analysisMaxEstimatedInputTokens: "8000",
  analysisTraceVerbose: false,
  llmGenerationTimeout: "120",
  maxBatchRetries: "3",
  maxConcurrentBatches: "1",
  analysisStrategyMode: "balanced",
  analysisTriggerThreshold: "50",
  retentionMessagesDays: "90",
  retentionAnalysisDays: "90",
  retentionLeaderboardDays: "90",
  retentionAppLogsDays: "30",
  retentionUserEventsDays: "365",
  autoPauseOnRetriesExhausted: true,
  weatherLocation: "system",
  uiLocale: "zh-Hant",
  agentHistoryMaxMessages: "40",
  agentHistoryMaxChars: "48000",
  assistantDisplayName: "",
  assistantAvatar: "",
  userDisplayName: "",
  userAvatar: "",
  userBackground: "",
};
