import type { SystemSettingsSnapshot } from "../types";

/** Default system settings snapshot for tests. */
export const defaultSettingsSnapshot: SystemSettingsSnapshot = {
  llmProvider: "ollama",
  analysisPaused: false,
  ollamaBaseUrl: "http://localhost:11434",
  ollamaModel: "llama3",
  ollamaThinkingEnabled: false,
  openaiBaseUrl: "",
  openaiModel: "",
  openaiApiKey: "",
  openaiJsonMode: "json_schema",
  geminiBaseUrl: "",
  geminiModel: "",
  geminiApiKey: "",
  openrouterBaseUrl: "",
  openrouterModel: "",
  openrouterApiKey: "",
  analysisBatchMessageLimit: "50",
  analysisMaxTotalChars: "100000",
  analysisMaxEstimatedInputTokens: "8000",
  analysisTraceVerbose: false,
  llmGenerationTimeout: "120",
  maxBatchRetries: "3",
  maxConcurrentBatches: "1",
  analysisStrategyMode: "balanced",
  analysisTriggerThreshold: "50",
  retentionMessagesDays: "90",
  retentionAnalysisDays: "90",
  retentionLeaderboardDays: "90",
  retentionAppLogsDays: "30",
  retentionUserEventsDays: "365",
  autoPauseOnRetriesExhausted: true,
  weatherLocation: "system",
  uiLocale: "zh-Hant",
  assistantWebSearchEnabled: true,
  webSearchProvider: "auto",
  braveSearchApiKey: "",
  assistantLlmProvider: "",
  assistantLlmBaseUrl: "",
  assistantLlmModel: "",
  assistantLlmApiKey: "",
  agentHistoryMaxMessages: "40",
  agentHistoryMaxChars: "48000",
  assistantDisplayName: "",
  assistantAvatar: "",
  userDisplayName: "",
  userAvatar: "",
  userBackground: "",
};
